name: tourmate_app
description: A Flutter app connecting tourists with local tour guides
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.3.3
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  image_picker: ^1.0.0
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  path_provider: ^2.1.4
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.67.0
  file_picker: ^10.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  windows:

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/l10n/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
